environments:
  dev-keycloak:
    values:
      - version: 0.0.1
      - env.d/{{ .Environment.Name }}/values.secrets.yaml
  dev-dinum:
    values:
      - version: 0.0.1
      - env.d/{{ .Environment.Name }}/values.secrets.yaml
  dev:
    values:
      - version: 0.0.1
      - env.d/{{ .Environment.Name }}/values.secrets.yaml

repositories:
- name: livekit
  url: https://helm.livekit.io

- name: dev-backends
  url: https://suitenumerique.github.io/helm-dev-backend

releases:
  - name: extra
    installed: {{ regexMatch "^dev.*" .Environment.Name | toYaml }}
    missingFileHandler: Warn
    namespace: {{ .Namespace }}
    chart: ./extra
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml
    values:
    - env.d/{{ .Environment.Name }}/values.meet.yaml.gotmpl
    - addRedirect: {{ .Values | get "addRedirect" "False" }}
      enablePermanentRedirect: {{ .Values | get "enablePermanentRedirect" "False"}}
      oldDomain: {{ .Values | get "oldDomain" "demo.com" }}
      newDomain: {{ .Values | get "newDomain" "demo.com" }}
    - realm: |
{{ readFile "../../docker/auth/realm.json" | replace "http://localhost:3200" "https://meet.127.0.0.1.nip.io" | indent 8 }}

  - name: meet
    version: {{ .Values.version }}
    namespace: {{ .Namespace }}
    missingFileHandler: Warn
    chart: ./meet
    values:
      - env.d/{{ .Environment.Name }}/values.meet.yaml.gotmpl
      - env.d/{{ .Environment.Name }}/values.secrets.yaml
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

  - name: livekit
    installed: {{ regexMatch "^dev.*" .Environment.Name | toYaml }}
    missingFileHandler: Warn
    namespace: {{ .Namespace }}
    chart: livekit/livekit-server
    values:
      - env.d/{{ .Environment.Name }}/values.livekit.yaml.gotmpl
      - env.d/{{ .Environment.Name }}/values.secrets.yaml
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

  - name: livekit-egress
    installed: {{ regexMatch "^dev.*" .Environment.Name | toYaml }}
    missingFileHandler: Warn
    namespace: {{ .Namespace }}
    chart: livekit/egress
    values:
      - env.d/{{ .Environment.Name }}/values.egress.yaml.gotmpl
      - env.d/{{ .Environment.Name }}/values.secrets.yaml
    secrets:
      - env.d/{{ .Environment.Name }}/secrets.enc.yaml

  - name: dev-backend
    namespace: {{ .Namespace }}
    chart: dev-backends/dev-backend
    version: 0.0.1
    values:
      - postgres:
          enabled: true
          name: postgres
          #serviceNameOverride: postgres
          image: postgres:16-alpine
          username: dinum
          password: pass
          database: dinum
          size: 1Gi
      - redis:
          enabled: true
          name: redis
          #serviceNameOverride: redis
          image: redis:8.2-alpine
          username: user
          password: pass
      - minio:
          enabled: true
          image: minio/minio
          name: minio
          #serviceNameOverride: minio
          hostname: minio.127.0.0.1.nip.io
          tls:
            enabled: true
            secretName: meet-tls
          username: dinum
          password: password
          bucket: meet-media-storage
          size: 1Gi
      - keycloak:
          enabled: true
          image: quay.io/keycloak/keycloak:20.0.1
          name: keycloak
          #serviceNameOverride: keycloak
          hostname: keycloak.127.0.0.1.nip.io
          username: admin
          password: pass
          tls:
            enabled: true
            secretName: meet-tls
          db:
            username: dinum
            password: pass
            database: keycloak
            size: 1Gi
            image: postgres:16-alpine
          realm:
            name: meet
            username: meet
            password: meet
            email: meet@example.com

