---
apiVersion: v1
kind: Service
metadata:
  name: kc-postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: tcp-postgresql
    port: 5432
    protocol: TCP
    targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/instance: extra
    app.kubernetes.io/name: kc-postgresql
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kc-postgresql
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: extra
      app.kubernetes.io/name: kc-postgresql
  serviceName: "kc-postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: extra
        app.kubernetes.io/name: kc-postgresql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pg
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: tcp-postgresql
        env:
          - name: POSTGRES_PASSWORD
            value: pass
          - name: POSTGRES_USER
            value: dinum
          - name: POSTGRES_DB
            value: keycloak
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

