{{- if .Values.frontend.outlookAddon.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: outlook-addon-config
  namespace: {{ .Release.Namespace }}
data:
  config.js: |
    window.__APP_CONFIG__ = {
      BASE_URL: {{ .Values.frontend.outlookAddon.baseUrl | quote }},
      APP_NAME: {{ .Values.frontend.outlookAddon.appName | quote }}
    };
{{- end }}
