# Generated by Django 5.2.9 on 2025-12-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='Recording options', verbose_name='Recording options'),
        ),
    ]
