# Generated by Django 5.2.11 on 2026-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_recording_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(help_text='The language in which the user wants to see the interface.', max_length=10, verbose_name='language', blank=True),
        ),
    ]
