# Generated by Django 5.2.12 on 2026-03-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='active',
            new_name='is_active',
        ),
    ]
