# Generated by Django 5.2.11 on 2026-02-27 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='users',
            field=models.ManyToManyField(related_name='resources', through='core.ResourceAccess', through_fields=('resource', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
