# Generated by Django 5.2.14 on 2026-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_active_application_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready')], max_length=25),
        ),
    ]
