# Generated by Django 5.2.14 on 2026-06-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_unique_email_when_sub_is_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='upload_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready')], max_length=25),
        ),
    ]
