# Generated by Django 5.2.12 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_room_is_encrypted_user_default_encryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='encryption_paused',
            field=models.BooleanField(default=False, help_text='Temporarily suspend E2EE so external devices can join.', verbose_name='Encryption paused'),
        ),
    ]
