# Generated by Django 5.2.14 on 2026-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_recording_external_process_id_alter_recording_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_room_access_level',
            field=models.CharField(blank=True, choices=[('public', 'Public Access'), ('trusted', 'Trusted Access'), ('restricted', 'Restricted Access')], help_text='Access level applied by default to new rooms created by this user. When empty, the instance default is used.', max_length=50, null=True, verbose_name='default room access level'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_room_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Configurations applied by default to new rooms created by this user.', verbose_name='default room configuration'),
        ),
    ]
