# Generated by Django 5.2.14 on 2026-09-16 19:23

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_user_default_room_access_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public Access'), ('trusted', 'Trusted Access'), ('restricted', 'Restricted Access')], default='public', max_length=50, validators=[core.models.validate_access_level]),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_room_access_level',
            field=models.CharField(blank=True, choices=[('public', 'Public Access'), ('trusted', 'Trusted Access'), ('restricted', 'Restricted Access')], help_text='Access level applied by default to new rooms created by this user. When empty, the instance default is used.', max_length=50, null=True, validators=[core.models.validate_access_level], verbose_name='default room access level'),
        ),
    ]
