# Generated by Django 5.2.16 on 2026-09-07 17:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_user_default_room_access_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("rooms:create", "Create rooms"),
                        ("rooms:list", "List rooms"),
                        ("rooms:retrieve", "Retrieve room details"),
                        ("rooms:update", "Update rooms"),
                        ("rooms:delete", "Delete rooms"),
                        (
                            "rooms:grant-access",
                            "Grant access to another user on a room",
                        ),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
