# Generated by Django 5.2.16 on 2026-10-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_room_last_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="claims",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="OIDC userinfo claims selected by OIDC_USERINFO_STORED_CLAIMS.",
            ),
        ),
    ]
