# Generated by Django 5.2.14 on 2026-10-03 14:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_room_last_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakoutSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakout_sessions', to='core.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Breakout session',
                'verbose_name_plural': 'Breakout sessions',
                'db_table': 'meet_breakout_session',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BreakoutRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Position')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.breakoutsession', verbose_name='Breakout session')),
            ],
            options={
                'verbose_name': 'Breakout room',
                'verbose_name_plural': 'Breakout rooms',
                'db_table': 'meet_breakout_room',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='BreakoutAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('identity', models.CharField(max_length=255, verbose_name='Participant identity')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Participant name')),
                ('breakout_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.breakoutroom', verbose_name='Breakout room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.breakoutsession', verbose_name='Breakout session')),
            ],
            options={
                'verbose_name': 'Breakout assignment',
                'verbose_name_plural': 'Breakout assignments',
                'db_table': 'meet_breakout_assignment',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='breakoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('room',), name='unique_active_breakout_session_per_room'),
        ),
        migrations.AddConstraint(
            model_name='breakoutassignment',
            constraint=models.UniqueConstraint(fields=('session', 'identity'), name='unique_breakout_assignment_per_identity'),
        ),
    ]
