# Generated by Django 5.2.14 on 2026-10-07 18:45

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models
from django.db.models.functions import Upper


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0025_application_client_secret_sha256'),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="user",
            index=models.Index(
                Upper("email"),
                name="user_email_upper_idx",
            ),
        ),
    ]
